/*
 * !!! AUTOGENERATED FILE !!!
 *
 * Do not edit manually!
 * Run 'yarn genrootfs' to regenerate
 * 
 */
import { DSFilePerms, DSFileSystem, DSIDirectory, DSInode } from "./dsFileSystem";
import { DSIProcessFile } from "./filesystem/dsIProcessFile";
import { DSIWebFile } from "./filesystem/dsIWebFile";
import { DSRAMFileSystem } from "./filesystem/dsRAMFileSystem";

// WEBFILE TRAVERSAL IMPORTS
import { PRCat } from "./rootfs/base/bin/cat";
import { PRCaterpillar } from "./rootfs/base/bin/caterpillar";
import { PRCHMod } from "./rootfs/base/bin/chmod";
import { PRTestAnim } from "./rootfs/base/bin/demoanim";
import { PRDemoCurses } from "./rootfs/base/bin/democurses";
import { PRDemoMarkdown } from "./rootfs/base/bin/demomarkdown";
import { PRDemoMouseTouch } from "./rootfs/base/bin/demomousetouch";
import { PRDSMDBrowser } from "./rootfs/base/bin/dsmdbrowser";
import { DSShell } from "./rootfs/base/bin/dssh";
import { PREcho } from "./rootfs/base/bin/echo";
import { PREdit } from "./rootfs/base/bin/edit";
import { PREnv } from "./rootfs/base/bin/env";
import { PRFSViewer } from "./rootfs/base/bin/fsviewer";
import { PRImgview } from "./rootfs/base/bin/imgview";
import { PRInit } from "./rootfs/base/bin/init";
import { PRLess } from "./rootfs/base/bin/less";
import { PRLs } from "./rootfs/base/bin/ls";
import { PRMan } from "./rootfs/base/bin/man";
import { PRMkdir } from "./rootfs/base/bin/mkdir";
import { PRMount } from "./rootfs/base/bin/mount";
import { PRPixelAssault } from "./rootfs/base/bin/pixelassault";
import { PRPs } from "./rootfs/base/bin/ps";
import { PRPwd } from "./rootfs/base/bin/pwd";
import { PRReset } from "./rootfs/base/bin/reset";
import { PRSleep } from "./rootfs/base/bin/sleep";
import { PRSplash } from "./rootfs/base/bin/splash";
import { PRTouch } from "./rootfs/base/bin/touch";
import rootfs_base_data_app_dsmdbrowser_404_dsmd from "./rootfs/base/data/app/dsmdbrowser/404.dsmd";
import rootfs_base_data_app_fsviewer_foldericon_png from "./rootfs/base/data/app/fsviewer/foldericon.png";
import rootfs_base_data_app_fsviewer_fsvieweropen_dsmd from "./rootfs/base/data/app/fsviewer/fsvieweropen.dsmd";
import rootfs_base_data_app_fsviewer_imageicon_png from "./rootfs/base/data/app/fsviewer/imageicon.png";
import rootfs_base_data_app_fsviewer_texticon_png from "./rootfs/base/data/app/fsviewer/texticon.png";
import rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile000_png from "./rootfs/base/data/app/pixel_assault/Enemies/Alien1/tile000.png";
import rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile001_png from "./rootfs/base/data/app/pixel_assault/Enemies/Alien1/tile001.png";
import rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile002_png from "./rootfs/base/data/app/pixel_assault/Enemies/Alien1/tile002.png";
import rootfs_base_data_app_pixel_assault_Enemies_blub_blub1_png from "./rootfs/base/data/app/pixel_assault/Enemies/blub/blub1.png";
import rootfs_base_data_app_pixel_assault_Enemies_blub_blub2_png from "./rootfs/base/data/app/pixel_assault/Enemies/blub/blub2.png";
import rootfs_base_data_app_pixel_assault_Enemies_enemygreen_gif from "./rootfs/base/data/app/pixel_assault/Enemies/enemygreen.gif";
import rootfs_base_data_app_pixel_assault_Enemies_grab_grab1_png from "./rootfs/base/data/app/pixel_assault/Enemies/grab/grab1.png";
import rootfs_base_data_app_pixel_assault_Enemies_grab_grab2_png from "./rootfs/base/data/app/pixel_assault/Enemies/grab/grab2.png";
import rootfs_base_data_app_pixel_assault_Enemies_grab_grab3_png from "./rootfs/base/data/app/pixel_assault/Enemies/grab/grab3.png";
import rootfs_base_data_app_pixel_assault_Enemies_paranoid_gif from "./rootfs/base/data/app/pixel_assault/Enemies/paranoid.gif";
import rootfs_base_data_app_pixel_assault_PixelAssaultSplash2_png from "./rootfs/base/data/app/pixel_assault/PixelAssaultSplash2.png";
import rootfs_base_data_app_pixel_assault_background_jpg from "./rootfs/base/data/app/pixel_assault/background.jpg";
import rootfs_base_data_app_pixel_assault_bonuses_bulletbonus_png from "./rootfs/base/data/app/pixel_assault/bonuses/bulletbonus.png";
import rootfs_base_data_app_pixel_assault_bonuses_heartbonus_png from "./rootfs/base/data/app/pixel_assault/bonuses/heartbonus.png";
import rootfs_base_data_app_pixel_assault_bonuses_scorebonus_png from "./rootfs/base/data/app/pixel_assault/bonuses/scorebonus.png";
import rootfs_base_data_app_pixel_assault_bonuses_shieldbonus_png from "./rootfs/base/data/app/pixel_assault/bonuses/shieldbonus.png";
import rootfs_base_data_app_pixel_assault_bonuses_speedbonus_png from "./rootfs/base/data/app/pixel_assault/bonuses/speedbonus.png";
import rootfs_base_data_app_pixel_assault_bullet_png from "./rootfs/base/data/app/pixel_assault/bullet.png";
import rootfs_base_data_app_pixel_assault_enemybullet_png from "./rootfs/base/data/app/pixel_assault/enemybullet.png";
import rootfs_base_data_app_pixel_assault_heartanim_gif from "./rootfs/base/data/app/pixel_assault/heartanim.gif";
import rootfs_base_data_app_pixel_assault_numbers_digit0_png from "./rootfs/base/data/app/pixel_assault/numbers/digit0.png";
import rootfs_base_data_app_pixel_assault_numbers_digit1_png from "./rootfs/base/data/app/pixel_assault/numbers/digit1.png";
import rootfs_base_data_app_pixel_assault_numbers_digit2_png from "./rootfs/base/data/app/pixel_assault/numbers/digit2.png";
import rootfs_base_data_app_pixel_assault_numbers_digit3_png from "./rootfs/base/data/app/pixel_assault/numbers/digit3.png";
import rootfs_base_data_app_pixel_assault_numbers_digit4_png from "./rootfs/base/data/app/pixel_assault/numbers/digit4.png";
import rootfs_base_data_app_pixel_assault_numbers_digit5_png from "./rootfs/base/data/app/pixel_assault/numbers/digit5.png";
import rootfs_base_data_app_pixel_assault_numbers_digit6_png from "./rootfs/base/data/app/pixel_assault/numbers/digit6.png";
import rootfs_base_data_app_pixel_assault_numbers_digit7_png from "./rootfs/base/data/app/pixel_assault/numbers/digit7.png";
import rootfs_base_data_app_pixel_assault_numbers_digit8_png from "./rootfs/base/data/app/pixel_assault/numbers/digit8.png";
import rootfs_base_data_app_pixel_assault_numbers_digit9_png from "./rootfs/base/data/app/pixel_assault/numbers/digit9.png";
import rootfs_base_data_app_pixel_assault_pixelsplosion_gif from "./rootfs/base/data/app/pixel_assault/pixelsplosion.gif";
import rootfs_base_data_app_pixel_assault_player_lightning0_png from "./rootfs/base/data/app/pixel_assault/player/lightning0.png";
import rootfs_base_data_app_pixel_assault_player_lightning1_png from "./rootfs/base/data/app/pixel_assault/player/lightning1.png";
import rootfs_base_data_app_pixel_assault_player_lightning2_png from "./rootfs/base/data/app/pixel_assault/player/lightning2.png";
import rootfs_base_data_app_pixel_assault_player_lightning3_png from "./rootfs/base/data/app/pixel_assault/player/lightning3.png";
import rootfs_base_data_app_pixel_assault_shieldpiece_png from "./rootfs/base/data/app/pixel_assault/shieldpiece.png";
import rootfs_base_data_app_pixel_assault_shieldpiece10_png from "./rootfs/base/data/app/pixel_assault/shieldpiece10.png";
import rootfs_base_data_app_pixel_assault_shieldpiece3_png from "./rootfs/base/data/app/pixel_assault/shieldpiece3.png";
import rootfs_base_data_app_pixel_assault_shieldpiece6_png from "./rootfs/base/data/app/pixel_assault/shieldpiece6.png";
import rootfs_base_data_demo_animation_32x32_A_png from "./rootfs/base/data/demo/animation/32x32_A.png";
import rootfs_base_data_demo_animation_32x32_B_png from "./rootfs/base/data/demo/animation/32x32_B.png";
import rootfs_base_data_demo_animation_32x32_C_png from "./rootfs/base/data/demo/animation/32x32_C.png";
import rootfs_base_data_demo_dssh_samplescript_dssh from "./rootfs/base/data/demo/dssh/samplescript.dssh";
import rootfs_base_data_demo_image_gorzocrop_png from "./rootfs/base/data/demo/image/gorzocrop.png";
import rootfs_base_data_demo_image_worldturning_gif from "./rootfs/base/data/demo/image/worldturning.gif";
import rootfs_base_data_demo_markdown_32x32_testpattern_png from "./rootfs/base/data/demo/markdown/32x32_testpattern.png";
import rootfs_base_data_demo_markdown_demomarkdown_dsmd from "./rootfs/base/data/demo/markdown/demomarkdown.dsmd";
import rootfs_base_data_demo_mousetouch_pointer_png from "./rootfs/base/data/demo/mousetouch/pointer.png";
import rootfs_base_data_demo_text_bazisa_txt from "./rootfs/base/data/demo/text/bazisa.txt";
import rootfs_base_data_man__template_dsmd from "./rootfs/base/data/man/_template.dsmd";
import rootfs_base_data_man_cat_dsmd from "./rootfs/base/data/man/cat.dsmd";
import rootfs_base_data_man_caterpillar_dsmd from "./rootfs/base/data/man/caterpillar.dsmd";
import rootfs_base_data_man_chmod_dsmd from "./rootfs/base/data/man/chmod.dsmd";
import rootfs_base_data_man_demoanim_dsmd from "./rootfs/base/data/man/demoanim.dsmd";
import rootfs_base_data_man_democurses_dsmd from "./rootfs/base/data/man/democurses.dsmd";
import rootfs_base_data_man_demomarkdown_dsmd from "./rootfs/base/data/man/demomarkdown.dsmd";
import rootfs_base_data_man_demomousetouch_dsmd from "./rootfs/base/data/man/demomousetouch.dsmd";
import rootfs_base_data_man_dsmdbrowser_dsmd from "./rootfs/base/data/man/dsmdbrowser.dsmd";
import rootfs_base_data_man_dssh_dsmd from "./rootfs/base/data/man/dssh.dsmd";
import rootfs_base_data_man_echo_dsmd from "./rootfs/base/data/man/echo.dsmd";
import rootfs_base_data_man_edit_dsmd from "./rootfs/base/data/man/edit.dsmd";
import rootfs_base_data_man_env_dsmd from "./rootfs/base/data/man/env.dsmd";
import rootfs_base_data_man_fsviewer_dsmd from "./rootfs/base/data/man/fsviewer.dsmd";
import rootfs_base_data_man_imgview_dsmd from "./rootfs/base/data/man/imgview.dsmd";
import rootfs_base_data_man_init_dsmd from "./rootfs/base/data/man/init.dsmd";
import rootfs_base_data_man_less_dsmd from "./rootfs/base/data/man/less.dsmd";
import rootfs_base_data_man_ls_dsmd from "./rootfs/base/data/man/ls.dsmd";
import rootfs_base_data_man_man_dsmd from "./rootfs/base/data/man/man.dsmd";
import rootfs_base_data_man_mkdir_dsmd from "./rootfs/base/data/man/mkdir.dsmd";
import rootfs_base_data_man_mount_dsmd from "./rootfs/base/data/man/mount.dsmd";
import rootfs_base_data_man_pixelassault_dsmd from "./rootfs/base/data/man/pixelassault.dsmd";
import rootfs_base_data_man_ps_dsmd from "./rootfs/base/data/man/ps.dsmd";
import rootfs_base_data_man_pwd_dsmd from "./rootfs/base/data/man/pwd.dsmd";
import rootfs_base_data_man_reset_dsmd from "./rootfs/base/data/man/reset.dsmd";
import rootfs_base_data_man_sleep_dsmd from "./rootfs/base/data/man/sleep.dsmd";
import rootfs_base_data_man_splash_dsmd from "./rootfs/base/data/man/splash.dsmd";
import rootfs_base_etc_autoexec_dssh from "./rootfs/base/etc/autoexec.dssh";
import rootfs_base_etc_deprecated_systems_incorporated_txt from "./rootfs/base/etc/deprecated_systems_incorporated.txt";
import rootfs_base_etc_depsys_txt from "./rootfs/base/etc/depsys.txt";

// BUILDROOTFS HEADER
export function buildrootfs(): DSFileSystem {
    const fs = new DSRAMFileSystem();

    // WEBFILE TRAVERSAL HEADER
    let dirstack: DSIDirectory[] = [];
    let curdir = fs.root;
    let curfile: DSIWebFile;
    let binfile: DSInode;

    // WEBFILE TRAVERSAL BODY

    // Traversing bin
    dirstack.push(curdir);
    curdir = curdir.mkdir('bin');
    
    binfile = new DSIProcessFile(fs, PRCat);
    curdir.addfile("cat", binfile);
     
    binfile = new DSIProcessFile(fs, PRCaterpillar);
    curdir.addfile("caterpillar", binfile);
     
    binfile = new DSIProcessFile(fs, PRCHMod);
    curdir.addfile("chmod", binfile);
     
    binfile = new DSIProcessFile(fs, PRTestAnim);
    curdir.addfile("demoanim", binfile);
     
    binfile = new DSIProcessFile(fs, PRDemoCurses);
    curdir.addfile("democurses", binfile);
     
    binfile = new DSIProcessFile(fs, PRDemoMarkdown);
    curdir.addfile("demomarkdown", binfile);
     
    binfile = new DSIProcessFile(fs, PRDemoMouseTouch);
    curdir.addfile("demomousetouch", binfile);
     
    binfile = new DSIProcessFile(fs, PRDSMDBrowser);
    curdir.addfile("dsmdbrowser", binfile);
     
    binfile = new DSIProcessFile(fs, DSShell);
    curdir.addfile("dssh", binfile);
     
    binfile = new DSIProcessFile(fs, PREcho);
    curdir.addfile("echo", binfile);
     
    binfile = new DSIProcessFile(fs, PREdit);
    curdir.addfile("edit", binfile);
     
    binfile = new DSIProcessFile(fs, PREnv);
    curdir.addfile("env", binfile);
     
    binfile = new DSIProcessFile(fs, PRFSViewer);
    curdir.addfile("fsviewer", binfile);
     
    binfile = new DSIProcessFile(fs, PRImgview);
    curdir.addfile("imgview", binfile);
     
    binfile = new DSIProcessFile(fs, PRInit);
    curdir.addfile("init", binfile);
     
    binfile = new DSIProcessFile(fs, PRLess);
    curdir.addfile("less", binfile);
     
    binfile = new DSIProcessFile(fs, PRLs);
    curdir.addfile("ls", binfile);
     
    binfile = new DSIProcessFile(fs, PRMan);
    curdir.addfile("man", binfile);
     
    binfile = new DSIProcessFile(fs, PRMkdir);
    curdir.addfile("mkdir", binfile);
     
    binfile = new DSIProcessFile(fs, PRMount);
    curdir.addfile("mount", binfile);
     
    binfile = new DSIProcessFile(fs, PRPixelAssault);
    curdir.addfile("pixelassault", binfile);
     
    binfile = new DSIProcessFile(fs, PRPs);
    curdir.addfile("ps", binfile);
     
    binfile = new DSIProcessFile(fs, PRPwd);
    curdir.addfile("pwd", binfile);
     
    binfile = new DSIProcessFile(fs, PRReset);
    curdir.addfile("reset", binfile);
     
    binfile = new DSIProcessFile(fs, PRSleep);
    curdir.addfile("sleep", binfile);
     
    binfile = new DSIProcessFile(fs, PRSplash);
    curdir.addfile("splash", binfile);
     
    binfile = new DSIProcessFile(fs, PRTouch);
    curdir.addfile("touch", binfile);
     
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited bin
        
    // Traversing data
    dirstack.push(curdir);
    curdir = curdir.mkdir('data');
    
    // Traversing data/app
    dirstack.push(curdir);
    curdir = curdir.mkdir('app');
    
    // Traversing data/app/dsmdbrowser
    dirstack.push(curdir);
    curdir = curdir.mkdir('dsmdbrowser');
    
    // Creating data/app/dsmdbrowser/404.dsmd
    curfile = fs.createInode(rootfs_base_data_app_dsmdbrowser_404_dsmd) as DSIWebFile;
    curdir.addfile("404.dsmd", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/dsmdbrowser
        
    // Traversing data/app/fsviewer
    dirstack.push(curdir);
    curdir = curdir.mkdir('fsviewer');
    
    // Creating data/app/fsviewer/foldericon.png
    curfile = fs.createInode(rootfs_base_data_app_fsviewer_foldericon_png) as DSIWebFile;
    curdir.addfile("foldericon.png", curfile);
    
    // Creating data/app/fsviewer/fsvieweropen.dsmd
    curfile = fs.createInode(rootfs_base_data_app_fsviewer_fsvieweropen_dsmd) as DSIWebFile;
    curdir.addfile("fsvieweropen.dsmd", curfile);
    
    // Creating data/app/fsviewer/imageicon.png
    curfile = fs.createInode(rootfs_base_data_app_fsviewer_imageicon_png) as DSIWebFile;
    curdir.addfile("imageicon.png", curfile);
    
    // Creating data/app/fsviewer/texticon.png
    curfile = fs.createInode(rootfs_base_data_app_fsviewer_texticon_png) as DSIWebFile;
    curdir.addfile("texticon.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/fsviewer
        
    // Traversing data/app/pixel_assault
    dirstack.push(curdir);
    curdir = curdir.mkdir('pixel_assault');
    
    // Traversing data/app/pixel_assault/Enemies
    dirstack.push(curdir);
    curdir = curdir.mkdir('Enemies');
    
    // Traversing data/app/pixel_assault/Enemies/Alien1
    dirstack.push(curdir);
    curdir = curdir.mkdir('Alien1');
    
    // Creating data/app/pixel_assault/Enemies/Alien1/tile000.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile000_png) as DSIWebFile;
    curdir.addfile("tile000.png", curfile);
    
    // Creating data/app/pixel_assault/Enemies/Alien1/tile001.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile001_png) as DSIWebFile;
    curdir.addfile("tile001.png", curfile);
    
    // Creating data/app/pixel_assault/Enemies/Alien1/tile002.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_Alien1_tile002_png) as DSIWebFile;
    curdir.addfile("tile002.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/Enemies/Alien1
        
    // Traversing data/app/pixel_assault/Enemies/blub
    dirstack.push(curdir);
    curdir = curdir.mkdir('blub');
    
    // Creating data/app/pixel_assault/Enemies/blub/blub1.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_blub_blub1_png) as DSIWebFile;
    curdir.addfile("blub1.png", curfile);
    
    // Creating data/app/pixel_assault/Enemies/blub/blub2.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_blub_blub2_png) as DSIWebFile;
    curdir.addfile("blub2.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/Enemies/blub
        
    // Traversing data/app/pixel_assault/Enemies/grab
    dirstack.push(curdir);
    curdir = curdir.mkdir('grab');
    
    // Creating data/app/pixel_assault/Enemies/grab/grab1.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_grab_grab1_png) as DSIWebFile;
    curdir.addfile("grab1.png", curfile);
    
    // Creating data/app/pixel_assault/Enemies/grab/grab2.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_grab_grab2_png) as DSIWebFile;
    curdir.addfile("grab2.png", curfile);
    
    // Creating data/app/pixel_assault/Enemies/grab/grab3.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_grab_grab3_png) as DSIWebFile;
    curdir.addfile("grab3.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/Enemies/grab
        
    // Creating data/app/pixel_assault/Enemies/enemygreen.gif
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_enemygreen_gif) as DSIWebFile;
    curdir.addfile("enemygreen.gif", curfile);
    
    // Creating data/app/pixel_assault/Enemies/paranoid.gif
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_Enemies_paranoid_gif) as DSIWebFile;
    curdir.addfile("paranoid.gif", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/Enemies
        
    // Traversing data/app/pixel_assault/bonuses
    dirstack.push(curdir);
    curdir = curdir.mkdir('bonuses');
    
    // Creating data/app/pixel_assault/bonuses/bulletbonus.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bonuses_bulletbonus_png) as DSIWebFile;
    curdir.addfile("bulletbonus.png", curfile);
    
    // Creating data/app/pixel_assault/bonuses/heartbonus.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bonuses_heartbonus_png) as DSIWebFile;
    curdir.addfile("heartbonus.png", curfile);
    
    // Creating data/app/pixel_assault/bonuses/scorebonus.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bonuses_scorebonus_png) as DSIWebFile;
    curdir.addfile("scorebonus.png", curfile);
    
    // Creating data/app/pixel_assault/bonuses/shieldbonus.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bonuses_shieldbonus_png) as DSIWebFile;
    curdir.addfile("shieldbonus.png", curfile);
    
    // Creating data/app/pixel_assault/bonuses/speedbonus.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bonuses_speedbonus_png) as DSIWebFile;
    curdir.addfile("speedbonus.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/bonuses
        
    // Traversing data/app/pixel_assault/numbers
    dirstack.push(curdir);
    curdir = curdir.mkdir('numbers');
    
    // Creating data/app/pixel_assault/numbers/digit0.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit0_png) as DSIWebFile;
    curdir.addfile("digit0.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit1.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit1_png) as DSIWebFile;
    curdir.addfile("digit1.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit2.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit2_png) as DSIWebFile;
    curdir.addfile("digit2.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit3.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit3_png) as DSIWebFile;
    curdir.addfile("digit3.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit4.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit4_png) as DSIWebFile;
    curdir.addfile("digit4.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit5.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit5_png) as DSIWebFile;
    curdir.addfile("digit5.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit6.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit6_png) as DSIWebFile;
    curdir.addfile("digit6.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit7.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit7_png) as DSIWebFile;
    curdir.addfile("digit7.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit8.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit8_png) as DSIWebFile;
    curdir.addfile("digit8.png", curfile);
    
    // Creating data/app/pixel_assault/numbers/digit9.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_numbers_digit9_png) as DSIWebFile;
    curdir.addfile("digit9.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/numbers
        
    // Traversing data/app/pixel_assault/player
    dirstack.push(curdir);
    curdir = curdir.mkdir('player');
    
    // Creating data/app/pixel_assault/player/lightning0.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_player_lightning0_png) as DSIWebFile;
    curdir.addfile("lightning0.png", curfile);
    
    // Creating data/app/pixel_assault/player/lightning1.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_player_lightning1_png) as DSIWebFile;
    curdir.addfile("lightning1.png", curfile);
    
    // Creating data/app/pixel_assault/player/lightning2.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_player_lightning2_png) as DSIWebFile;
    curdir.addfile("lightning2.png", curfile);
    
    // Creating data/app/pixel_assault/player/lightning3.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_player_lightning3_png) as DSIWebFile;
    curdir.addfile("lightning3.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault/player
        
    // Creating data/app/pixel_assault/PixelAssaultSplash2.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_PixelAssaultSplash2_png) as DSIWebFile;
    curdir.addfile("PixelAssaultSplash2.png", curfile);
    
    // Creating data/app/pixel_assault/background.jpg
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_background_jpg) as DSIWebFile;
    curdir.addfile("background.jpg", curfile);
    
    // Creating data/app/pixel_assault/bullet.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_bullet_png) as DSIWebFile;
    curdir.addfile("bullet.png", curfile);
    
    // Creating data/app/pixel_assault/enemybullet.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_enemybullet_png) as DSIWebFile;
    curdir.addfile("enemybullet.png", curfile);
    
    // Creating data/app/pixel_assault/heartanim.gif
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_heartanim_gif) as DSIWebFile;
    curdir.addfile("heartanim.gif", curfile);
    
    // Creating data/app/pixel_assault/pixelsplosion.gif
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_pixelsplosion_gif) as DSIWebFile;
    curdir.addfile("pixelsplosion.gif", curfile);
    
    // Creating data/app/pixel_assault/shieldpiece.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_shieldpiece_png) as DSIWebFile;
    curdir.addfile("shieldpiece.png", curfile);
    
    // Creating data/app/pixel_assault/shieldpiece10.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_shieldpiece10_png) as DSIWebFile;
    curdir.addfile("shieldpiece10.png", curfile);
    
    // Creating data/app/pixel_assault/shieldpiece3.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_shieldpiece3_png) as DSIWebFile;
    curdir.addfile("shieldpiece3.png", curfile);
    
    // Creating data/app/pixel_assault/shieldpiece6.png
    curfile = fs.createInode(rootfs_base_data_app_pixel_assault_shieldpiece6_png) as DSIWebFile;
    curdir.addfile("shieldpiece6.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app/pixel_assault
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/app
        
    // Traversing data/demo
    dirstack.push(curdir);
    curdir = curdir.mkdir('demo');
    
    // Traversing data/demo/animation
    dirstack.push(curdir);
    curdir = curdir.mkdir('animation');
    
    // Creating data/demo/animation/32x32_A.png
    curfile = fs.createInode(rootfs_base_data_demo_animation_32x32_A_png) as DSIWebFile;
    curdir.addfile("32x32_A.png", curfile);
    
    // Creating data/demo/animation/32x32_B.png
    curfile = fs.createInode(rootfs_base_data_demo_animation_32x32_B_png) as DSIWebFile;
    curdir.addfile("32x32_B.png", curfile);
    
    // Creating data/demo/animation/32x32_C.png
    curfile = fs.createInode(rootfs_base_data_demo_animation_32x32_C_png) as DSIWebFile;
    curdir.addfile("32x32_C.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/animation
        
    // Traversing data/demo/dssh
    dirstack.push(curdir);
    curdir = curdir.mkdir('dssh');
    
    // Creating data/demo/dssh/samplescript.dssh
    curfile = fs.createInode(rootfs_base_data_demo_dssh_samplescript_dssh) as DSIWebFile;
    curdir.addfile("samplescript.dssh", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/dssh
        
    // Traversing data/demo/image
    dirstack.push(curdir);
    curdir = curdir.mkdir('image');
    
    // Creating data/demo/image/gorzocrop.png
    curfile = fs.createInode(rootfs_base_data_demo_image_gorzocrop_png) as DSIWebFile;
    curdir.addfile("gorzocrop.png", curfile);
    
    // Creating data/demo/image/worldturning.gif
    curfile = fs.createInode(rootfs_base_data_demo_image_worldturning_gif) as DSIWebFile;
    curdir.addfile("worldturning.gif", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/image
        
    // Traversing data/demo/markdown
    dirstack.push(curdir);
    curdir = curdir.mkdir('markdown');
    
    // Creating data/demo/markdown/32x32_testpattern.png
    curfile = fs.createInode(rootfs_base_data_demo_markdown_32x32_testpattern_png) as DSIWebFile;
    curdir.addfile("32x32_testpattern.png", curfile);
    
    // Creating data/demo/markdown/demomarkdown.dsmd
    curfile = fs.createInode(rootfs_base_data_demo_markdown_demomarkdown_dsmd) as DSIWebFile;
    curdir.addfile("demomarkdown.dsmd", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/markdown
        
    // Traversing data/demo/mousetouch
    dirstack.push(curdir);
    curdir = curdir.mkdir('mousetouch');
    
    // Creating data/demo/mousetouch/pointer.png
    curfile = fs.createInode(rootfs_base_data_demo_mousetouch_pointer_png) as DSIWebFile;
    curdir.addfile("pointer.png", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/mousetouch
        
    // Traversing data/demo/text
    dirstack.push(curdir);
    curdir = curdir.mkdir('text');
    
    // Creating data/demo/text/bazisa.txt
    curfile = fs.createInode(rootfs_base_data_demo_text_bazisa_txt) as DSIWebFile;
    curdir.addfile("bazisa.txt", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo/text
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/demo
        
    // Traversing data/man
    dirstack.push(curdir);
    curdir = curdir.mkdir('man');
    
    // Creating data/man/_template.dsmd
    curfile = fs.createInode(rootfs_base_data_man__template_dsmd) as DSIWebFile;
    curdir.addfile("_template.dsmd", curfile);
    
    // Creating data/man/cat.dsmd
    curfile = fs.createInode(rootfs_base_data_man_cat_dsmd) as DSIWebFile;
    curdir.addfile("cat.dsmd", curfile);
    
    // Creating data/man/caterpillar.dsmd
    curfile = fs.createInode(rootfs_base_data_man_caterpillar_dsmd) as DSIWebFile;
    curdir.addfile("caterpillar.dsmd", curfile);
    
    // Creating data/man/chmod.dsmd
    curfile = fs.createInode(rootfs_base_data_man_chmod_dsmd) as DSIWebFile;
    curdir.addfile("chmod.dsmd", curfile);
    
    // Creating data/man/demoanim.dsmd
    curfile = fs.createInode(rootfs_base_data_man_demoanim_dsmd) as DSIWebFile;
    curdir.addfile("demoanim.dsmd", curfile);
    
    // Creating data/man/democurses.dsmd
    curfile = fs.createInode(rootfs_base_data_man_democurses_dsmd) as DSIWebFile;
    curdir.addfile("democurses.dsmd", curfile);
    
    // Creating data/man/demomarkdown.dsmd
    curfile = fs.createInode(rootfs_base_data_man_demomarkdown_dsmd) as DSIWebFile;
    curdir.addfile("demomarkdown.dsmd", curfile);
    
    // Creating data/man/demomousetouch.dsmd
    curfile = fs.createInode(rootfs_base_data_man_demomousetouch_dsmd) as DSIWebFile;
    curdir.addfile("demomousetouch.dsmd", curfile);
    
    // Creating data/man/dsmdbrowser.dsmd
    curfile = fs.createInode(rootfs_base_data_man_dsmdbrowser_dsmd) as DSIWebFile;
    curdir.addfile("dsmdbrowser.dsmd", curfile);
    
    // Creating data/man/dssh.dsmd
    curfile = fs.createInode(rootfs_base_data_man_dssh_dsmd) as DSIWebFile;
    curdir.addfile("dssh.dsmd", curfile);
    
    // Creating data/man/echo.dsmd
    curfile = fs.createInode(rootfs_base_data_man_echo_dsmd) as DSIWebFile;
    curdir.addfile("echo.dsmd", curfile);
    
    // Creating data/man/edit.dsmd
    curfile = fs.createInode(rootfs_base_data_man_edit_dsmd) as DSIWebFile;
    curdir.addfile("edit.dsmd", curfile);
    
    // Creating data/man/env.dsmd
    curfile = fs.createInode(rootfs_base_data_man_env_dsmd) as DSIWebFile;
    curdir.addfile("env.dsmd", curfile);
    
    // Creating data/man/fsviewer.dsmd
    curfile = fs.createInode(rootfs_base_data_man_fsviewer_dsmd) as DSIWebFile;
    curdir.addfile("fsviewer.dsmd", curfile);
    
    // Creating data/man/imgview.dsmd
    curfile = fs.createInode(rootfs_base_data_man_imgview_dsmd) as DSIWebFile;
    curdir.addfile("imgview.dsmd", curfile);
    
    // Creating data/man/init.dsmd
    curfile = fs.createInode(rootfs_base_data_man_init_dsmd) as DSIWebFile;
    curdir.addfile("init.dsmd", curfile);
    
    // Creating data/man/less.dsmd
    curfile = fs.createInode(rootfs_base_data_man_less_dsmd) as DSIWebFile;
    curdir.addfile("less.dsmd", curfile);
    
    // Creating data/man/ls.dsmd
    curfile = fs.createInode(rootfs_base_data_man_ls_dsmd) as DSIWebFile;
    curdir.addfile("ls.dsmd", curfile);
    
    // Creating data/man/man.dsmd
    curfile = fs.createInode(rootfs_base_data_man_man_dsmd) as DSIWebFile;
    curdir.addfile("man.dsmd", curfile);
    
    // Creating data/man/mkdir.dsmd
    curfile = fs.createInode(rootfs_base_data_man_mkdir_dsmd) as DSIWebFile;
    curdir.addfile("mkdir.dsmd", curfile);
    
    // Creating data/man/mount.dsmd
    curfile = fs.createInode(rootfs_base_data_man_mount_dsmd) as DSIWebFile;
    curdir.addfile("mount.dsmd", curfile);
    
    // Creating data/man/pixelassault.dsmd
    curfile = fs.createInode(rootfs_base_data_man_pixelassault_dsmd) as DSIWebFile;
    curdir.addfile("pixelassault.dsmd", curfile);
    
    // Creating data/man/ps.dsmd
    curfile = fs.createInode(rootfs_base_data_man_ps_dsmd) as DSIWebFile;
    curdir.addfile("ps.dsmd", curfile);
    
    // Creating data/man/pwd.dsmd
    curfile = fs.createInode(rootfs_base_data_man_pwd_dsmd) as DSIWebFile;
    curdir.addfile("pwd.dsmd", curfile);
    
    // Creating data/man/reset.dsmd
    curfile = fs.createInode(rootfs_base_data_man_reset_dsmd) as DSIWebFile;
    curdir.addfile("reset.dsmd", curfile);
    
    // Creating data/man/sleep.dsmd
    curfile = fs.createInode(rootfs_base_data_man_sleep_dsmd) as DSIWebFile;
    curdir.addfile("sleep.dsmd", curfile);
    
    // Creating data/man/splash.dsmd
    curfile = fs.createInode(rootfs_base_data_man_splash_dsmd) as DSIWebFile;
    curdir.addfile("splash.dsmd", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data/man
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited data
        
    // Traversing etc
    dirstack.push(curdir);
    curdir = curdir.mkdir('etc');
    
    // Creating etc/autoexec.dssh
    curfile = fs.createInode(rootfs_base_etc_autoexec_dssh) as DSIWebFile;
    curdir.addfile("autoexec.dssh", curfile);
    
    // Creating etc/deprecated_systems_incorporated.txt
    curfile = fs.createInode(rootfs_base_etc_deprecated_systems_incorporated_txt) as DSIWebFile;
    curdir.addfile("deprecated_systems_incorporated.txt", curfile);
    
    // Creating etc/depsys.txt
    curfile = fs.createInode(rootfs_base_etc_depsys_txt) as DSIWebFile;
    curdir.addfile("depsys.txt", curfile);
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited etc
        
    // BUILDROOTFS FOOTER
    fs.root.chmod(DSFilePerms.rx());
    fs.readonly = true;

    return fs;
}
